graph TD
  %% exec d-comment
  %% exec a-comment
  A["データ取得"]
  B["前処理"]
  C["モデル訓練"]
  D["特徴量エンジニアリング"]
  E["評価"]
  F["デプロイ"]
  End

  A --> B
  B --> C
  B --> D
  C --> E
  D --> E
  E --> F
  %% コメント

	classDef some fill:#f96 
	classDef some2 fill:#191